import {CalendarClock, Mail, PackageCheck, Target} from 'lucide-react'
import {useCallback,useEffect,useState} from 'react'
import {api,formatDateTime,money} from '../lib/api'
import {connectRealtime} from '../lib/realtime'
import {StatCard} from '../components/StatCard'
import {useAuth} from '../lib/auth'

type Dash={revenue_today_cents:number;revenue_week_cents:number;revenue_month_cents:number;units_week:number;units_target:number;units_missing:number;units_percent:number;next_appointment:any;today_appointments:any[];active_rentals:number;unread_messages:number}
export function DashboardPage(){const {me}=useAuth();const [d,setD]=useState<Dash|null>(null);const load=useCallback(()=>api<Dash>('/dashboard').then(setD),[]);useEffect(()=>{load();return connectRealtime(()=>load())},[load]);if(!d)return <div className="loading">Dashboard wird geladen…</div>;return <div className="page"><div className="page-head"><div><h1>Willkommen zurück, {me?.full_name.split(' ')[0]}!</h1><p>Hier ist dein aktueller Vertriebsüberblick.</p></div></div><div className="stat-grid"><StatCard label="Umsatz heute" value={money(d.revenue_today_cents)} accent="green"/><StatCard label="Umsatz Woche" value={money(d.revenue_week_cents)} accent="green"/><StatCard label="Umsatz Monat" value={money(d.revenue_month_cents)}/><StatCard label="Noch bis 30 Einheiten" value={`${d.units_missing}`} accent={d.units_missing===0?'green':'orange'}/></div><div className="dashboard-grid"><section className="card big"><div className="section-title"><Target size={20}/><h2>Wochenziel</h2></div><div className="units-line"><strong>{d.units_week}</strong><span>/ {d.units_target} Einheiten</span></div><div className="progress"><span style={{width:`${Math.min(d.units_percent,100)}%`}}/></div><p>{d.units_percent}% erreicht · {d.units_missing} Einheiten fehlen</p></section><section className="card"><div className="section-title"><CalendarClock size={20}/><h2>Nächster Termin</h2></div>{d.next_appointment?<><h3>{d.next_appointment.customer_name}</h3><p>{formatDateTime(d.next_appointment.start_at)}</p><small>{d.next_appointment.address||'Keine Adresse hinterlegt'}</small></>:<p>Kein kommender Termin.</p>}</section><section className="card"><div className="section-title"><CalendarClock size={20}/><h2>Heute</h2></div>{d.today_appointments.length?d.today_appointments.map(a=><div className="list-row" key={a.id}><strong>{new Date(a.start_at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</strong><span>{a.customer_name}</span></div>):<p>Heute keine Termine.</p>}</section><section className="card"><div className="section-title"><PackageCheck size={20}/><h2>Verleihgeräte</h2></div><div className="hero-number">{d.active_rentals}</div><p>aktive Geräte im Verleih</p></section><section className="card"><div className="section-title"><Mail size={20}/><h2>Nachrichten</h2></div><div className="hero-number">{d.unread_messages}</div><p>ungelesene Nachrichten</p></section></div></div>}
