import {FormEvent,useEffect,useState} from 'react'
import {Send} from 'lucide-react'
import {api,formatDateTime} from '../lib/api'
import {connectRealtime} from '../lib/realtime'
import {useAuth} from '../lib/auth'
import {useToast} from '../components/Toast'

type Msg={id:string;sender_user_id:string;sender_name:string;recipient_user_id:string|null;recipient_name:string;body:string;created_at:string;read_at:string|null}
type U={id:string;full_name:string;role:string}
export function MessagesPage(){const {me}=useAuth();const [rows,setRows]=useState<Msg[]>([]);const [users,setUsers]=useState<U[]>([]);const [recipient,setRecipient]=useState('');const [body,setBody]=useState('');const toast=useToast();const load=()=>api<Msg[]>('/messages').then(setRows);useEffect(()=>{load();api<U[]>('/directory/users').then(setUsers);return connectRealtime(e=>{if(e.type==='message.new')load()})},[]);async function send(e:FormEvent){e.preventDefault();try{await api('/messages',{method:'POST',body:JSON.stringify({recipient_user_id:recipient||null,body})});setBody('');load()}catch(err){toast(err instanceof Error?err.message:'Fehler','error')}}return <div className="page"><div className="page-head"><div><h1>Nachrichten</h1><p>Interne Einzel- und Teamnachrichten in Echtzeit.</p></div></div><div className="messages-layout"><section className="card messages-feed">{rows.map(m=><div className={m.sender_user_id===me?.id?'message mine':'message'} key={m.id}><div><strong>{m.sender_name}</strong><small>{formatDateTime(m.created_at)} · an {m.recipient_name}</small></div><p>{m.body}</p></div>)}{!rows.length&&<div className="empty">Noch keine Nachrichten.</div>}</section><form className="card message-compose" onSubmit={send}><h2>Neue Nachricht</h2><label>Empfänger<select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Teamchat</option>{users.filter(u=>u.id!==me?.id).map(u=><option key={u.id} value={u.id}>{u.full_name}{u.role==='TEAM_LEADER'?' · TL':''}</option>)}</select></label><label>Nachricht<textarea required value={body} onChange={e=>setBody(e.target.value)} rows={8}/></label><button className="primary"><Send size={18}/> Senden</button></form></div></div>}
